quarkus.datasource.db2.db-kind=db2
quarkus.datasource.db2.jdbc.url=jdbc:db2://localhost:50000/testdb2
quarkus.datasource.db2.username= db2inst1
quarkus.datasource.db2.password= my_password2

quarkus.datasource.duckdb.db-kind=other
quarkus.datasource.duckdb.jdbc.driver=org.duckdb.DuckDBDriver
quarkus.datasource.duckdb.jdbc.url=jdbc:duckdb::memory:?cache=shared